apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: dev  
rules:
- apiGroups: ["", "apps", "extensions", "networking.k8s.io", "batch"]
  resources: ["*"] 
  verbs: ["*"]