pipeline {
    agent any

    environment {
        REGISTRY = "docker.io/omar4700"
        Docker_Cred = credentials('DockerHub-Credentials')
        NAMESPACE = "dev"
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo "Checking out code..."
                checkout scmGit(
                    branches: [[name: '*/main']],
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/Omarh4700/Projects.git']]
                )
            }
        }

        stage('Build Images') {
            steps {
                script {
                    echo "Building Docker images with tag: ${BUILD_NUMBER}"
                    sh """
                        docker build -t ${REGISTRY}/backend:${BUILD_NUMBER} ./backend
                        docker build -t ${REGISTRY}/proxy:${BUILD_NUMBER} ./proxy
                        docker build -t ${REGISTRY}/database:${BUILD_NUMBER} ./database
                    """
                }
            }
        }

        stage('Push Images') {
            steps {
                script {
                    echo "Pushing Docker images to registry..."
                    sh """
                        echo $Docker_Cred_PSW | docker login -u $Docker_Cred_USR --password-stdin
                        docker push ${REGISTRY}/backend:${BUILD_NUMBER}
                        docker push ${REGISTRY}/proxy:${BUILD_NUMBER}
                        docker push ${REGISTRY}/database:${BUILD_NUMBER}
                    """
                }
            }
        }

        stage('Deploy to K8s using Helm') {
            steps {
                script {
                    echo "Deploying application to Kubernetes using Helm..."
                    sh """
                        helm upgrade --install myapp ./helm-chart \
                        --namespace ${NAMESPACE} \
                        --set backend.image=${REGISTRY}/backend:${BUILD_NUMBER} \
                        --set proxy.image=${REGISTRY}/proxy:${BUILD_NUMBER} \
                        --set database.image=${REGISTRY}/database:${BUILD_NUMBER}
                    """
                }
            }
        }
    }

    post {
        success {
            mail to: 'hassanomar4700@gmail.com',
                 subject: "Jenkins Build #${BUILD_NUMBER} Succeeded",
                 body: "The Jenkins build #${BUILD_NUMBER} has completed successfully."
        }
        failure {
            mail to: 'hassanomar4700@gmail.com',
                 subject: " Jenkins Build #${BUILD_NUMBER} Failed",
                 body: "The Jenkins build #${BUILD_NUMBER} has failed. Please check the logs."
        }
    }
}
