# --- SERVICE for the BACKEND API (Go App) ---
# This exposes the Go application on a static port on each node in the cluster.
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  # Exposes the service on each Node's IP at a static port.
  type: NodePort 
  selector:
    # This must match the labels in your backend_deployment.yaml
    app: api 
  ports:
    - protocol: TCP
      # Port that the service is exposed on internally within the cluster.
      port: 8000
      # Port that the container is listening on.
      targetPort: 8000 